[package]

description = "A usable Cassandra CQL driver (this replaces the previous cql-ffi package).\nWraps the DataStax c++ native driver and uses cql-bindgen via rust-bindgen.\nWorks with nightly"
keywords = ["cassandra"]
license = "Apache-2.0"
homepage = "https://github.com/metaswitch/cassandra-rs"
repository = "https://github.com/metaswitch/cassandra-rs"
name = "cassandra"
version = "0.8.2-pre"
authors = ["Tupshin Harper <tupshin@tupshin.com>", "Keith Wansbrough <Keith.Wansbrough@metaswitch.com>"]
build = "build.rs"
publish = false

[dependencies]
clippy = {version = "0.0", optional = true}
libc = "0.2"
num = "0.1"
log = "0.3"
cassandra-sys = "0.8"
decimal = "0.2"
chrono = "0.2"
ip = "1.0"
time = "0.1"
clap = "1"
uuid = "0.1"
error-chain="0.10"

[build-dependencies]
rusty-cheddar = "0.3"

